// <auto-generated />
using System;
using Code_First_Task_NewsPortal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Code_First_Task_NewsPortal.Migrations
{
    [DbContext(typeof(NewsPortalContext))]
    partial class NewsPortalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Code_First_Task_NewsPortal.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 35,
                            Email = "john@example.com",
                            Name = "John Smith",
                            NationalId = "A123456",
                            Password = "1234",
                            PhoneNumber = "01011111111"
                        },
                        new
                        {
                            Id = 2,
                            Age = 29,
                            Email = "sara@example.com",
                            Name = "Sara Ali",
                            NationalId = "B987654",
                            Password = "5678",
                            PhoneNumber = "01022222222"
                        });
                });

            modelBuilder.Entity("Code_First_Task_NewsPortal.Models.Catalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Catalogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Political news and updates",
                            Name = "Politics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sports news and events",
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Latest technology trends",
                            Name = "Technology"
                        });
                });

            modelBuilder.Entity("Code_First_Task_NewsPortal.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CatalogId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("Time")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CatalogId");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CatalogId = 1,
                            Date = new DateOnly(2025, 9, 15),
                            Description = "The results of the national election...",
                            Time = new TimeSpan(0, 14, 30, 0, 0),
                            Title = "Election Results"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CatalogId = 2,
                            Date = new DateOnly(2025, 9, 14),
                            Description = "Final match of the championship...",
                            Time = new TimeSpan(0, 20, 0, 0, 0),
                            Title = "Football Championship"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            CatalogId = 3,
                            Date = new DateOnly(2025, 9, 13),
                            Description = "New AI model surpasses human performance...",
                            Time = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "AI Breakthrough"
                        });
                });

            modelBuilder.Entity("Code_First_Task_NewsPortal.Models.News", b =>
                {
                    b.HasOne("Code_First_Task_NewsPortal.Models.Author", "Author")
                        .WithMany("NewsList")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Code_First_Task_NewsPortal.Models.Catalog", "Catalog")
                        .WithMany("News")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("Code_First_Task_NewsPortal.Models.Author", b =>
                {
                    b.Navigation("NewsList");
                });

            modelBuilder.Entity("Code_First_Task_NewsPortal.Models.Catalog", b =>
                {
                    b.Navigation("News");
                });
#pragma warning restore 612, 618
        }
    }
}
